<a href="https://colab.research.google.com/github/Ramyanaidu02/RNN/blob/main/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
data = pd.read_csv('spam.csv',encoding='latin-1')

In [ ]:
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [ ]:
data.rename(columns={'v1':'target','v2':'text'},inplace=True)

In [ ]:
data.head()

target                                               text Unnamed: 2  \
0    ham  Go until jurong point, crazy.. Available only ...        NaN   
1    ham                      Ok lar... Joking wif u oni...        NaN   
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3    ham  U dun say so early hor... U c already then say...        NaN   
4    ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [ ]:
vectorizer = CountVectorizer(stop_words='english')

In [ ]:
X = vectorizer.fit_transform(data['text'])

In [ ]:
X

<5572x8404 sparse matrix of type '<class 'numpy.int64'>'
	with 43478 stored elements in Compressed Sparse Row format>

In [ ]:
feature_matrix = X.toarray()

In [ ]:
feature_matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
print(vectorizer.get_feature_names_out())

['00' '000' '000pes' ... 'ûïharry' 'ûò' 'ûówell']


In [ ]:
df_features = pd.DataFrame(feature_matrix,columns=vectorizer.get_feature_names_out())
print(df_features)

      00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0      0    0       0             0     0     0            0            0   
1      0    0       0             0     0     0            0            0   
2      0    0       0             0     0     0            0            0   
3      0    0       0             0     0     0            0            0   
4      0    0       0             0     0     0            0            0   
...   ..  ...     ...           ...   ...   ...          ...          ...   
5567   0    0       0             0     0     0            0            0   
5568   0    0       0             0     0     0            0            0   
5569   0    0       0             0     0     0            0            0   
5570   0    0       0             0     0     0            0            0   
5571   0    0       0             0     0     0            0            0   

      0125698789  02  ...  ó_  û_  û_thanks  ûªm  ûªt  ûªve  ûï  ûïharry  û

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score


In [ ]:
X_train,X_test,y_train,y_test= train_test_split(feature_matrix,data['target'],test_size= 0.2,random_state=42)

In [ ]:
sv = SVC(kernel='linear')

In [ ]:
sv.fit(X_train,y_train)

SVC(kernel='linear')

In [ ]:
y_pred = sv.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.9802690582959641


In [ ]:
new_message = ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005, Test FA to 87121 to receive entry question(std txt rate)T&C's apply 084521810075over18's"]
new_message_vectorized = vectorizer.transform(new_message)
new_message_features = new_message_vectorized.toarray()


In [ ]:
predict_message = sv.predict(new_message_features)


In [ ]:
predicted_label = predict_message[0]

In [ ]:
print(f'the message is classified as: {predicted_label}')

the message is classified as: spam


In [ ]:
import pandas as pd
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,SimpleRNN
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [ ]:
spam_data = pd.read_csv('spam.csv',encoding='latin-1')

In [ ]:
spam_data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [ ]:
spam_data.rename(columns={'v1':'target','v2':'text'},inplace=True)

In [ ]:
spam_data= spam_data[['text','target']]

In [ ]:
le = LabelEncoder()
spam_data['target'] = le.fit_transform(spam_data['target'])

In [ ]:
spam_data

text  target
0     Go until jurong point, crazy.. Available only ...       0
1                         Ok lar... Joking wif u oni...       0
2     Free entry in 2 a wkly comp to win FA Cup fina...       1
3     U dun say so early hor... U c already then say...       0
4     Nah I don't think he goes to usf, he lives aro...       0
...                                                 ...     ...
5567  This is the 2nd time we have tried 2 contact u...       1
5568              Will Ì_ b going to esplanade fr home?       0
5569  Pity, * was in mood for that. So...any other s...       0
5570  The guy did some bitching but I acted like i'd...       0
5571                         Rofl. Its true to its name       0

[5572 rows x 2 columns]

In [ ]:
vacob_size = 1000

In [ ]:
encoded_docs =[one_hot(d,vacob_size)for d in spam_data['text']]

In [ ]:
max_length=50
padded_docs = pad_sequences(encoded_docs,maxlen=max_length,padding='post')

In [ ]:
labels = spam_data['target'].values

In [ ]:
labels

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(padded_docs,labels,test_size=0.2,random_state=42)

In [ ]:
y_train.shape

(4457,)

In [ ]:
#Build RNN
model = Sequential()
model.add(Embedding(vacob_size,100,input_length=max_length))
model.add(SimpleRNN(128))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(X_train,y_train,epochs=5,batch_size=32)

Epoch 1/5
140/140 ━━━━━━━━━━━━━━━━━━━━ 6s 27ms/step - accuracy: 0.8789 - loss: 0.3471
Epoch 2/5
140/140 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - accuracy: 0.9628 - loss: 0.1304
Epoch 3/5
140/140 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - accuracy: 0.9628 - loss: 0.1277
Epoch 4/5
140/140 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - accuracy: 0.9582 - loss: 0.1348
Epoch 5/5
140/140 ━━━━━━━━━━━━━━━━━━━━ 5s 25ms/step - accuracy: 0.9377 - loss: 0.1865


In [ ]:
loss,accuracy=model.evaluate(X_test,y_test)
print(f'test accuracy:{accuracy}')

35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9437 - loss: 0.1599
test accuracy:0.9327354431152344


In [ ]:
def predict_data(model,sentence,vocab_size,max_length):
    encoded_sentence = one_hot(sentence,vocab_size)
    padded_sentence = pad_sequences([encoded_sentence],maxlen=max_length,padding='post')
    prediction = model.predict(padded_sentence)
    return 'ham' if prediction>0.5 else 'spam'

In [ ]:
new_sentence = "congratulations you won a ticket"

In [ ]:
print(predict_data(model,new_sentence,vacob_size,max_length))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
ham


athelets example

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
data = pd.read_csv('athletes new.csv',encoding='latin-1')

In [ ]:
data.head()

code                 name       name_short              name_tv  gender  \
0  1535420   VALENCIA Alejandra       VALENCIA A   Alejandra VALENCIA  Female   
1  1535429          RUIZ Angela           RUIZ A          Angela RUIZ  Female   
2  1535430        GRANDE Matias         GRANDE M        Matias GRANDE    Male   
3  1536460         ROJAS Carlos          ROJAS C         Carlos ROJAS    Male   
4  1536467  MARTINEZ WING Bruno  MARTINEZ WING B  Bruno MARTINEZ WING    Male   

  function country_code country country_full nationality nationality_full  \
0  Athlete          MEX  Mexico       Mexico      Mexico           Mexico   
1  Athlete          MEX  Mexico       Mexico      Mexico           Mexico   
2  Athlete          MEX  Mexico       Mexico      Mexico           Mexico   
3  Athlete          MEX  Mexico       Mexico      Mexico           Mexico   
4  Athlete          MEX  Mexico       Mexico      Mexico           Mexico   

  nationality_code  height  weight  disciplines  \
0              MEX       0     0.0  ['Archery']   
1              MEX       0     0.0  ['Archery']   
2              MEX       0     0.0  ['Archery']   
3              MEX       0     0.0  ['Archery']   
4              MEX       0     0.0  ['Archery']   

                                              events  birth_date  
0  ["Women's Individual", "Women's Team", 'Mixed ...  1994-10-17  
1             ["Women's Individual", "Women's Team"]  2006-07-28  
2   ["Men's Individual", "Men's Team", 'Mixed Team']  2004-04-26  
3                 ["Men's Individual", "Men's Team"]  2000-01-14  
4                 ["Men's Individual", "Men's Team"]  1998-03-08

In [ ]:
data.rename(columns={'code':'target','name':'text'},inplace=True)

In [ ]:
data.head()

target                 text       name_short              name_tv  gender  \
0  1535420   VALENCIA Alejandra       VALENCIA A   Alejandra VALENCIA  Female   
1  1535429          RUIZ Angela           RUIZ A          Angela RUIZ  Female   
2  1535430        GRANDE Matias         GRANDE M        Matias GRANDE    Male   
3  1536460         ROJAS Carlos          ROJAS C         Carlos ROJAS    Male   
4  1536467  MARTINEZ WING Bruno  MARTINEZ WING B  Bruno MARTINEZ WING    Male   

  function country_code country country_full nationality nationality_full  \
0  Athlete          MEX  Mexico       Mexico      Mexico           Mexico   
1  Athlete          MEX  Mexico       Mexico      Mexico           Mexico   
2  Athlete          MEX  Mexico       Mexico      Mexico           Mexico   
3  Athlete          MEX  Mexico       Mexico      Mexico           Mexico   
4  Athlete          MEX  Mexico       Mexico      Mexico           Mexico   

  nationality_code  height  weight  disciplines  \
0              MEX       0     0.0  ['Archery']   
1              MEX       0     0.0  ['Archery']   
2              MEX       0     0.0  ['Archery']   
3              MEX       0     0.0  ['Archery']   
4              MEX       0     0.0  ['Archery']   

                                              events  birth_date  
0  ["Women's Individual", "Women's Team", 'Mixed ...  1994-10-17  
1             ["Women's Individual", "Women's Team"]  2006-07-28  
2   ["Men's Individual", "Men's Team", 'Mixed Team']  2004-04-26  
3                 ["Men's Individual", "Men's Team"]  2000-01-14  
4                 ["Men's Individual", "Men's Team"]  1998-03-08

In [ ]:
data = data[['text','target']]

In [ ]:
data.head()

text   target
0   VALENCIA Alejandra  1535420
1          RUIZ Angela  1535429
2        GRANDE Matias  1535430
3         ROJAS Carlos  1536460
4  MARTINEZ WING Bruno  1536467

In [ ]:
vectorizer = CountVectorizer(stop_words='english')

In [ ]:
X = vectorizer.fit_transform(data['text'])

In [ ]:
X

<11115x14800 sparse matrix of type '<class 'numpy.int64'>'
	with 24316 stored elements in Compressed Sparse Row format>

In [ ]:
feature_matrix = X.toarray()

In [ ]:
feature_matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
print(vectorizer.get_feature_names_out())

['671' 'aaberg' 'aaboe' ... 'zwicker' 'zwolinska' 'zyl']


In [ ]:
df_features = pd.DataFrame(feature_matrix,columns=vectorizer.get_feature_names_out())
print(df_features)

       671  aaberg  aaboe  aagaard  aagot  aalen  aaliyah  aan  aanholt  \
0        0       0      0        0      0      0        0    0        0   
1        0       0      0        0      0      0        0    0        0   
2        0       0      0        0      0      0        0    0        0   
3        0       0      0        0      0      0        0    0        0   
4        0       0      0        0      0      0        0    0        0   
...    ...     ...    ...      ...    ...    ...      ...  ...      ...   
11110    0       0      0        0      0      0        0    0        0   
11111    0       0      0        0      0      0        0    0        0   
11112    0       0      0        0      0      0        0    0        0   
11113    0       0      0        0      0      0        0    0        0   
11114    0       0      0        0      0      0        0    0        0   

       aardahl  ...  zuvela  zuzana  zuzanna  zvegelj  zverev  zvonimir  \
0            0  ...     

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score


In [ ]:
X_train,X_test,y_train,y_test = train_test_split(feature_matrix,data['target'],test_size= 0.2,random_state=42)